# Use postgres/example user/password credentials
services:
  # The dev oidc server needs to be visible to the Civiform server and web browsers
  # on the same host:port. Developers need to add a localhost IP alias for this
  # container name in their /etc/hosts file for the web brower to load the auth url.
  # EG: 127.0.0.1 dev-oidc
  dev-oidc:
    image: quay.io/keycloak/keycloak:26.0
    ports:
      - 3390:3390
    environment:
      KC_HOSTNAME: dev-oidc
      KC_HOSTNAME_PORT: 3390
      KC_HTTP_PORT: 3390
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: example
      KC_DB_SCHEMA: public
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_URL_DATABASE: keycloak
    depends_on:
      - db
    command: start --import-realm
    volumes:
      - ./keycloak/auth/import:/opt/keycloak/data/import

  civiform:
    image: civiform-dev
    links:
      - 'db:database'
      - 'mock-web-services'
      - 'dev-oidc'
    depends_on:
      - dev-oidc
    expose:
      - '9000'
      - '8457'
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-test}
      - AWS_REGION
      - SENDER_EMAIL_ADDRESS
      - EMAIL_PROVIDER
      - AWS_S3_BUCKET_NAME
      - AWS_S3_PUBLIC_BUCKET_NAME
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID:-test}
      - AZURE_LOCAL_CONNECTION_STRING
      - AZURE_STORAGE_ACCOUNT_NAME
      - AZURE_STORAGE_ACCOUNT_CONTAINER_NAME
      - CIVIFORM_TIME_ZONE_ID
      - STORAGE_SERVICE_NAME
      - LOGIN_RADIUS_API_KEY
      - LOGIN_RADIUS_METADATA_URI
      - LOGIN_RADIUS_SAML_APP_NAME
      - LOGIN_RADIUS_PRIVATE_KEY_PASS
      - LOGIN_RADIUS_KEYSTORE_PASS
      - LOGIN_RADIUS_KEYSTORE_NAME
      - CIVIFORM_APPLICANT_IDP=keycloak-applicant
      - CIVIFORM_ADMIN_IDP=keycloak-admin
      # Hard coded in test-support/test_oidc_provider.js
      - IDCS_CLIENT_ID=idcs-fake-oidc-client
      - IDCS_SECRET=idcs-fake-oidc-secret
      - IDCS_DISCOVERY_URI=http://dev-oidc:3390/.well-known/openid-configuration
      - IDCS_REGISTER_URI
      - APPLICANT_REGISTER_URI=http://dev-oidc:3390/realms/master/protocol/openid-connect/auth?client_id=applicant-client
      - ADFS_CLIENT_ID
      - ADFS_SECRET
      - ADMIN_OIDC_PROVIDER_NAME
      - ADMIN_OIDC_CLIENT_ID=admin-client
      - ADMIN_OIDC_CLIENT_SECRET=6YgUE89gbd1KeCPAuCjnU1v4AmiI4IcP # gitleaks:allow
      - ADMIN_OIDC_DISCOVERY_URI=http://dev-oidc:3390/realms/admin-realm/.well-known/openid-configuration
      - ADMIN_OIDC_RESPONSE_MODE
      - ADMIN_OIDC_RESPONSE_TYPE
      - ADMIN_OIDC_ADDITIONAL_SCOPES
      - ADMIN_OIDC_ADMIN_GROUP_NAME=/civiform_global_admin_group
      - APPLICANT_OIDC_POST_LOGOUT_REDIRECT_PARAM
      - APPLICANT_OIDC_LOGOUT_CLIENT_PARAM=client_id
      - APPLICANT_OIDC_OVERRIDE_LOGOUT_URL
      - APPLICANT_OIDC_PROVIDER_NAME
      - APPLICANT_OIDC_CLIENT_ID=applicant-client
      - APPLICANT_OIDC_CLIENT_SECRET=9ahHVoq5qu6Fussz1lf2AgLIzwrfLNqc # gitleaks:allow
      - APPLICANT_OIDC_DISCOVERY_URI=http://dev-oidc:3390/realms/applicant-realm/.well-known/openid-configuration
      - APPLICANT_OIDC_RESPONSE_MODE
      - APPLICANT_OIDC_RESPONSE_TYPE
      - APPLICANT_OIDC_ADDITIONAL_SCOPES
      - APPLICANT_OIDC_LOCALE_ATTRIBUTE
      - APPLICANT_OIDC_EMAIL_ATTRIBUTE
      - APPLICANT_OIDC_FIRST_NAME_ATTRIBUTE
      - APPLICANT_OIDC_MIDDLE_NAME_ATTRIBUTE
      - APPLICANT_OIDC_LAST_NAME_ATTRIBUTE
      - LOGIN_GOV_CLIENT_ID
      - LOGIN_GOV_DISCOVERY_URI
      - LOGIN_GOV_ADDITIONAL_SCOPES
      - LOGIN_GOV_ACR_VALUE
      - KEYCLOAK_APPLICANT_REALM=applicant-realm
      - KEYCLOAK_APPLICANT_BASE_URI=http://dev-oidc:3390
      - KEYCLOAK_ADMIN_REALM=admin-realm
      - KEYCLOAK_ADMIN_BASE_URI=http://dev-oidc:3390
      - CF_OPTIONAL_QUESTIONS
      - CIVIC_ENTITY_SMALL_LOGO_URL
      - WHITELABEL_CIVIC_ENTITY_SHORT_NAME
      - WHITELABEL_CIVIC_ENTITY_FULL_NAME
      - FAVICON_URL
      - DISABLE_ERRORPRONE=${DISABLE_ERRORPRONE:-false}
    entrypoint: /bin/bash
